databases:
  - name: Tepthon
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: Tepthon
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m Tepthon
    repo: https://github.com/Tepthonee/thesource      
    branch: main
   envVars:
      - key:  
        sync: false
      - key: API_HASH 
        sync: false
      - key: APP_ID 
        sync: false
      - key: STRING_SESSION
        sync: false                                                          
      - key: TG_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        sync: 3.10.6
      - key: DATABASE_URL
        fromDatabase:
          name: Tepthon
          property: connectionString
    autoDeploy: false
