databases:
  - name: Tepthon-db
    databaseName: Tepthon
    user: Tepthon
services:
  - type: web
    plan: free
    name: Tepthon
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m Tepthon
    repo: https://github.com/Tepthonee/thesource      
    branch: main
   - envVars:
      - key:  
        sync: false
      - key: API_HASH 
        sync: false
      - key: APP_ID 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false    
       - key: DATABASE_URL
        fromDatabase:
          name: Tepthon-db
          property: connectionString
    autoDeploy: false
